// Auto-generated by scripts/sync.mjs — do not edit by hand.
window.MENU_DATA = {
  "version": 1,
  "generatedAt": "2026-07-25T10:13:19.816Z",
  "supplements": [
    {
      "id": "supp-fairlife",
      "name": "Fairlife Protein Shake",
      "protein_g": 30,
      "calories": 150,
      "always_available": true
    },
    {
      "id": "supp-greek-yogurt",
      "name": "Greek Yogurt Cup",
      "protein_g": 15,
      "calories": 100,
      "always_available": true
    }
  ],
  "items": [
    {
      "id": "yogurt-fruit",
      "name": "Yogurt & Fruit",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "quick",
        "high-protein",
        "no-cook"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "greek yogurt"
        },
        {
          "name": "mixed fruit"
        }
      ],
      "nutrition": {
        "protein_g": 12,
        "calories": 329,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 167722
      }
    },
    {
      "id": "cottage-cheese-bowl",
      "name": "Cottage Cheese Bowl",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "quick",
        "high-protein",
        "no-cook"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "cottage cheese"
        },
        {
          "name": "mixed fruit"
        }
      ],
      "nutrition": {
        "protein_g": 33,
        "calories": 259,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2705751
      }
    },
    {
      "id": "avocado-toast-fruit",
      "name": "Avocado Toast & Fruit",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "quick"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "bread"
        },
        {
          "name": "avocado"
        },
        {
          "name": "mixed fruit"
        }
      ],
      "nutrition": {
        "protein_g": 8,
        "calories": 900,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2710208
      }
    },
    {
      "id": "toast-almond-butter-fruit",
      "name": "Almond Butter Toast & Fruit",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "quick"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "bread"
        },
        {
          "name": "almond butter"
        },
        {
          "name": "mixed fruit"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 900,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2707533
      }
    },
    {
      "id": "toast-butter-fruit",
      "name": "Buttered Toast & Fruit",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "quick"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "bread"
        },
        {
          "name": "butter"
        },
        {
          "name": "mixed fruit"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 900,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2707702
      }
    },
    {
      "id": "yogurt-bread",
      "name": "Yogurt & Bread",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "quick",
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "greek yogurt"
        },
        {
          "name": "bread"
        }
      ],
      "nutrition": {
        "protein_g": 14,
        "calories": 376,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 167722
      }
    },
    {
      "id": "boiled-eggs",
      "name": "Boiled Eggs",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "quick",
        "high-protein"
      ],
      "serving": {
        "amount": 2,
        "unit": "egg"
      },
      "ingredients": [
        {
          "name": "egg"
        }
      ],
      "nutrition": {
        "protein_g": 12,
        "calories": 143,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2707154
      }
    },
    {
      "id": "boiled-eggs-spiced",
      "name": "Spiced Boiled Eggs",
      "slots": [
        "breakfast"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "quick",
        "high-protein"
      ],
      "serving": {
        "amount": 2,
        "unit": "egg"
      },
      "ingredients": [
        {
          "name": "egg"
        },
        {
          "name": "chili powder"
        },
        {
          "name": "salt"
        }
      ],
      "nutrition": {
        "protein_g": 12,
        "calories": 143,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2707154
      }
    },
    {
      "id": "boiled-egg-yogurt",
      "name": "Boiled Egg & Yogurt",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "quick",
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "egg"
        },
        {
          "name": "greek yogurt"
        }
      ],
      "nutrition": {
        "protein_g": 45,
        "calories": 572,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2707154
      }
    },
    {
      "id": "boiled-egg-waffle",
      "name": "Boiled Egg & Waffle",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "quick",
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "egg"
        },
        {
          "name": "waffle"
        }
      ],
      "nutrition": {
        "protein_g": 45,
        "calories": 572,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2707154
      }
    },
    {
      "id": "scrambled-eggs",
      "name": "Scrambled Eggs",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "quick",
        "high-protein"
      ],
      "serving": {
        "amount": 2,
        "unit": "egg"
      },
      "ingredients": [
        {
          "name": "egg"
        },
        {
          "name": "butter"
        }
      ],
      "nutrition": {
        "protein_g": 10,
        "calories": 149,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 172187
      }
    },
    {
      "id": "scrambled-eggs-cheese",
      "name": "Scrambled Eggs with Cheese",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "quick",
        "high-protein"
      ],
      "serving": {
        "amount": 2,
        "unit": "egg"
      },
      "ingredients": [
        {
          "name": "egg"
        },
        {
          "name": "cheese"
        }
      ],
      "nutrition": {
        "protein_g": 10,
        "calories": 149,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 172187
      }
    },
    {
      "id": "omelette",
      "name": "Omelette",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "quick",
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "piece"
      },
      "ingredients": [
        {
          "name": "egg"
        },
        {
          "name": "onion"
        },
        {
          "name": "cheese"
        }
      ],
      "nutrition": {
        "protein_g": 25,
        "calories": 400,
        "carbs_g": null,
        "fat_g": null,
        "source": "ai-estimate",
        "confidence": "low",
        "fdcId": null
      }
    },
    {
      "id": "indian-scramble",
      "name": "Indian Egg Scramble (Akoori)",
      "slots": [
        "breakfast"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "quick",
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "egg"
        },
        {
          "name": "onion"
        },
        {
          "name": "tomato"
        },
        {
          "name": "green chili"
        },
        {
          "name": "cilantro"
        }
      ],
      "nutrition": {
        "protein_g": 25,
        "calories": 400,
        "carbs_g": null,
        "fat_g": null,
        "source": "ai-estimate",
        "confidence": "low",
        "fdcId": null
      }
    },
    {
      "id": "indian-omelette-cottage-cheese",
      "name": "Indian Omelette with Cottage Cheese",
      "slots": [
        "breakfast"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "egg"
        },
        {
          "name": "onion"
        },
        {
          "name": "tomato"
        },
        {
          "name": "green chili"
        },
        {
          "name": "cottage cheese"
        },
        {
          "name": "mixed fruit"
        }
      ],
      "nutrition": {
        "protein_g": 14,
        "calories": 576,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2705686
      }
    },
    {
      "id": "pizza-egg-tomato",
      "name": "Pizza Egg with Tomato",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "egg"
        },
        {
          "name": "tomato"
        },
        {
          "name": "cheese"
        }
      ],
      "nutrition": {
        "protein_g": 45,
        "calories": 900,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2708699
      }
    },
    {
      "id": "broccoli-cheddar-waffles-eggs",
      "name": "Savory Broccoli Cheddar Waffles with Eggs",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "broccoli"
        },
        {
          "name": "cheddar cheese"
        },
        {
          "name": "egg"
        },
        {
          "name": "flour"
        }
      ],
      "nutrition": {
        "protein_g": 4,
        "calories": 192,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 170989
      }
    },
    {
      "id": "dhokla",
      "name": "Dhokla (Vaghareli)",
      "slots": [
        "breakfast"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "steamed"
      ],
      "serving": {
        "amount": 4,
        "unit": "piece"
      },
      "ingredients": [
        {
          "name": "gram flour"
        },
        {
          "name": "greek yogurt"
        },
        {
          "name": "mustard seeds"
        },
        {
          "name": "curry leaves"
        }
      ],
      "nutrition": {
        "protein_g": 10,
        "calories": 400,
        "carbs_g": null,
        "fat_g": null,
        "source": "ai-estimate",
        "confidence": "low",
        "fdcId": null
      }
    },
    {
      "id": "bataka-poha",
      "name": "Bataka Poha",
      "slots": [
        "breakfast"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "quick"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "poha"
        },
        {
          "name": "potato"
        },
        {
          "name": "onion"
        },
        {
          "name": "peanuts"
        },
        {
          "name": "mustard seeds"
        }
      ],
      "nutrition": {
        "protein_g": 7,
        "calories": 186,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 173043
      }
    },
    {
      "id": "oat-bar-fruit",
      "name": "Oat Bar & Fruit",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "make-ahead",
        "quick"
      ],
      "serving": {
        "amount": 1,
        "unit": "bar"
      },
      "ingredients": [
        {
          "name": "oats"
        },
        {
          "name": "honey"
        },
        {
          "name": "mixed fruit"
        }
      ],
      "nutrition": {
        "protein_g": 6,
        "calories": 278,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 169063
      }
    },
    {
      "id": "chia-pudding",
      "name": "Chocolate Chia Pudding",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "make-ahead",
        "no-cook"
      ],
      "serving": {
        "amount": 1,
        "unit": "cup"
      },
      "ingredients": [
        {
          "name": "milk"
        },
        {
          "name": "maple syrup"
        },
        {
          "name": "dates"
        },
        {
          "name": "cocoa powder"
        },
        {
          "name": "chia seeds"
        }
      ],
      "nutrition": {
        "protein_g": 5,
        "calories": 341,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2705679
      }
    },
    {
      "id": "mango-smoothie",
      "name": "Mango Protein Smoothie",
      "slots": [
        "breakfast"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "quick",
        "high-protein",
        "no-cook"
      ],
      "serving": {
        "amount": 1,
        "unit": "glass"
      },
      "ingredients": [
        {
          "name": "mango"
        },
        {
          "name": "milk"
        },
        {
          "name": "vanilla protein powder"
        },
        {
          "name": "chia seeds"
        }
      ],
      "nutrition": {
        "protein_g": 22,
        "calories": 258,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2710147
      }
    },
    {
      "id": "sandwich",
      "name": "Sandwich",
      "slots": [
        "lunch"
      ],
      "cuisine": "American",
      "tags": [
        "quick"
      ],
      "serving": {
        "amount": 1,
        "unit": "sandwich"
      },
      "ingredients": [
        {
          "name": "bread"
        },
        {
          "name": "cheese"
        },
        {
          "name": "vegetables"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 900,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2708171
      }
    },
    {
      "id": "panini-sandwich",
      "name": "Panini Sandwich",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "Italian",
      "tags": [
        "quick"
      ],
      "serving": {
        "amount": 1,
        "unit": "sandwich"
      },
      "ingredients": [
        {
          "name": "bread"
        },
        {
          "name": "cheese"
        },
        {
          "name": "vegetables"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 900,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2708171
      }
    },
    {
      "id": "soup",
      "name": "Vegetable Soup",
      "slots": [
        "lunch"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "make-ahead"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "mixed vegetables"
        },
        {
          "name": "vegetable broth"
        }
      ],
      "nutrition": {
        "protein_g": 10,
        "calories": 400,
        "carbs_g": null,
        "fat_g": null,
        "source": "ai-estimate",
        "confidence": "low",
        "fdcId": null
      }
    },
    {
      "id": "mexican-soup",
      "name": "Mexican Soup",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "Mexican",
      "tags": [
        "vegetarian",
        "make-ahead"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "beans"
        },
        {
          "name": "tomato"
        },
        {
          "name": "corn"
        },
        {
          "name": "vegetable broth"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 872,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2708507
      }
    },
    {
      "id": "mini-idli",
      "name": "Mini Idli",
      "slots": [
        "lunch"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "steamed",
        "advance-prep"
      ],
      "serving": {
        "amount": 6,
        "unit": "piece"
      },
      "ingredients": [
        {
          "name": "idli"
        },
        {
          "name": "sambar"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 614,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2708346
      }
    },
    {
      "id": "vaghareli-idli",
      "name": "Vaghareli Idli",
      "slots": [
        "lunch"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "leftover-friendly"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "idli"
        },
        {
          "name": "mustard seeds"
        },
        {
          "name": "curry leaves"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 512,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2708346
      }
    },
    {
      "id": "chickpea-pasta-salad",
      "name": "Chickpea Pasta Salad",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "Mediterranean",
      "tags": [
        "vegetarian",
        "high-protein",
        "make-ahead"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "chickpea pasta"
        },
        {
          "name": "chickpeas"
        },
        {
          "name": "feta cheese"
        },
        {
          "name": "cucumber"
        },
        {
          "name": "tomato"
        },
        {
          "name": "olive oil"
        }
      ],
      "nutrition": {
        "protein_g": 24,
        "calories": 861,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2708947
      }
    },
    {
      "id": "lentil-salad",
      "name": "Lentil Salad",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "Mediterranean",
      "tags": [
        "vegetarian",
        "high-protein",
        "make-ahead"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "lentils"
        },
        {
          "name": "cucumber"
        },
        {
          "name": "tomato"
        },
        {
          "name": "onion"
        },
        {
          "name": "olive oil"
        }
      ],
      "nutrition": {
        "protein_g": 13,
        "calories": 389,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2707431
      }
    },
    {
      "id": "quesadilla",
      "name": "Quesadilla (Beans/Chicken)",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "Mexican",
      "tags": [
        "high-protein",
        "quick"
      ],
      "serving": {
        "amount": 1,
        "unit": "piece"
      },
      "ingredients": [
        {
          "name": "tortilla"
        },
        {
          "name": "cheese"
        },
        {
          "name": "beans"
        },
        {
          "name": "chicken"
        }
      ],
      "nutrition": {
        "protein_g": 12,
        "calories": 230,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2708593
      }
    },
    {
      "id": "cream-cheese-rolls-veggies",
      "name": "Cream Cheese Rolls with Veggies",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "quick"
      ],
      "serving": {
        "amount": 2,
        "unit": "roll"
      },
      "ingredients": [
        {
          "name": "tortilla"
        },
        {
          "name": "cream cheese"
        },
        {
          "name": "vegetables"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 567,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2707660
      }
    },
    {
      "id": "rajma-rice",
      "name": "Rajma & Rice",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "kidney beans"
        },
        {
          "name": "onion"
        },
        {
          "name": "tomato"
        },
        {
          "name": "rice"
        },
        {
          "name": "ginger"
        },
        {
          "name": "garlic"
        }
      ],
      "nutrition": {
        "protein_g": 25,
        "calories": 400,
        "carbs_g": null,
        "fat_g": null,
        "source": "ai-estimate",
        "confidence": "low",
        "fdcId": null
      }
    },
    {
      "id": "chana-dal-roti",
      "name": "Chana Dal with Roti",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "chana dal"
        },
        {
          "name": "onion"
        },
        {
          "name": "tomato"
        },
        {
          "name": "roti"
        }
      ],
      "nutrition": {
        "protein_g": 34,
        "calories": 580,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2707427
      }
    },
    {
      "id": "rice-dal",
      "name": "Rice & Dal",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "make-ahead",
        "freezer-friendly"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "rice"
        },
        {
          "name": "toor dal"
        },
        {
          "name": "ghee"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 448,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2709078
      }
    },
    {
      "id": "khichdi",
      "name": "Khichdi",
      "slots": [
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "quick",
        "comfort"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "rice"
        },
        {
          "name": "moong dal"
        },
        {
          "name": "ghee"
        }
      ],
      "nutrition": {
        "protein_g": 10,
        "calories": 400,
        "carbs_g": null,
        "fat_g": null,
        "source": "ai-estimate",
        "confidence": "low",
        "fdcId": null
      }
    },
    {
      "id": "idli-sambar",
      "name": "Idli & Sambar",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "steamed",
        "advance-prep"
      ],
      "serving": {
        "amount": 3,
        "unit": "piece"
      },
      "ingredients": [
        {
          "name": "idli"
        },
        {
          "name": "toor dal"
        },
        {
          "name": "mixed vegetables"
        },
        {
          "name": "sambar"
        }
      ],
      "nutrition": {
        "protein_g": 15,
        "calories": 307,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2708346
      }
    },
    {
      "id": "bhinda-kadhi",
      "name": "Bhinda Kadhi (Okra)",
      "slots": [
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "okra"
        },
        {
          "name": "greek yogurt"
        },
        {
          "name": "gram flour"
        },
        {
          "name": "rice"
        }
      ],
      "nutrition": {
        "protein_g": 10,
        "calories": 400,
        "carbs_g": null,
        "fat_g": null,
        "source": "ai-estimate",
        "confidence": "low",
        "fdcId": null
      }
    },
    {
      "id": "bataka-eggplant-sabzi",
      "name": "Bataka/Eggplant Sabzi with Roti/Rice",
      "slots": [
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "potato"
        },
        {
          "name": "eggplant"
        },
        {
          "name": "onion"
        },
        {
          "name": "tomato"
        },
        {
          "name": "roti"
        },
        {
          "name": "rice"
        }
      ],
      "nutrition": {
        "protein_g": 10,
        "calories": 400,
        "carbs_g": null,
        "fat_g": null,
        "source": "ai-estimate",
        "confidence": "low",
        "fdcId": null
      }
    },
    {
      "id": "moong-beans",
      "name": "Moong Beans Sabzi",
      "slots": [
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "moong beans"
        },
        {
          "name": "onion"
        },
        {
          "name": "tomato"
        }
      ],
      "nutrition": {
        "protein_g": 19,
        "calories": 417,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2707400
      }
    },
    {
      "id": "thiki-bhakri-cottage-cheese",
      "name": "Thick Bhakri with Cottage Cheese",
      "slots": [
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "high-protein"
      ],
      "serving": {
        "amount": 2,
        "unit": "piece"
      },
      "ingredients": [
        {
          "name": "millet flour"
        },
        {
          "name": "cottage cheese"
        }
      ],
      "nutrition": {
        "protein_g": 5,
        "calories": 190,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 170883
      }
    },
    {
      "id": "shahi-butter-paneer-roti",
      "name": "Shahi/Butter Paneer with Roti",
      "slots": [
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "paneer"
        },
        {
          "name": "tomato"
        },
        {
          "name": "cream"
        },
        {
          "name": "onion"
        },
        {
          "name": "roti"
        }
      ],
      "nutrition": {
        "protein_g": 25,
        "calories": 400,
        "carbs_g": null,
        "fat_g": null,
        "source": "ai-estimate",
        "confidence": "low",
        "fdcId": null
      }
    },
    {
      "id": "paneer-burger",
      "name": "Paneer Burger",
      "slots": [
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "burger"
      },
      "ingredients": [
        {
          "name": "paneer"
        },
        {
          "name": "burger bun"
        },
        {
          "name": "vegetables"
        }
      ],
      "nutrition": {
        "protein_g": 12,
        "calories": 222,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2709631
      }
    },
    {
      "id": "pav-bhaji",
      "name": "Pav Bhaji with Cauliflower",
      "slots": [
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "make-ahead"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "potato"
        },
        {
          "name": "cauliflower"
        },
        {
          "name": "peas"
        },
        {
          "name": "tomato"
        },
        {
          "name": "pav bun"
        },
        {
          "name": "butter"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 272,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2709633
      }
    },
    {
      "id": "hara-bhara-kebab-bbq",
      "name": "BBQ Hara Bhara Kebab",
      "slots": [
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian"
      ],
      "serving": {
        "amount": 3,
        "unit": "piece"
      },
      "ingredients": [
        {
          "name": "spinach"
        },
        {
          "name": "peas"
        },
        {
          "name": "potato"
        },
        {
          "name": "spices"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 900,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 171524
      }
    },
    {
      "id": "pulao",
      "name": "Vegetable Pulao",
      "slots": [
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "one-pot"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "basmati rice"
        },
        {
          "name": "mixed vegetables"
        },
        {
          "name": "spices"
        }
      ],
      "nutrition": {
        "protein_g": 8,
        "calories": 112,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 172284
      }
    },
    {
      "id": "biryani",
      "name": "Chicken Biryani",
      "slots": [
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "chicken"
        },
        {
          "name": "basmati rice"
        },
        {
          "name": "onion"
        },
        {
          "name": "greek yogurt"
        },
        {
          "name": "spices"
        }
      ],
      "nutrition": {
        "protein_g": 29,
        "calories": 416,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2706538
      }
    },
    {
      "id": "chicken-curry-naan-rice",
      "name": "Chicken Curry with Naan & Rice",
      "slots": [
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "high-protein",
        "leftover-friendly"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "chicken"
        },
        {
          "name": "onion"
        },
        {
          "name": "tomato"
        },
        {
          "name": "ginger"
        },
        {
          "name": "garlic"
        },
        {
          "name": "naan"
        },
        {
          "name": "rice"
        }
      ],
      "nutrition": {
        "protein_g": 26,
        "calories": 428,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2706437
      }
    },
    {
      "id": "butter-chicken-bake",
      "name": "Butter Chicken Bake",
      "slots": [
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "chicken"
        },
        {
          "name": "tomato"
        },
        {
          "name": "cream"
        },
        {
          "name": "butter"
        }
      ],
      "nutrition": {
        "protein_g": 45,
        "calories": 900,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2706069
      }
    },
    {
      "id": "egg-curry",
      "name": "Egg Curry",
      "slots": [
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "egg"
        },
        {
          "name": "onion"
        },
        {
          "name": "tomato"
        },
        {
          "name": "ginger"
        },
        {
          "name": "garlic"
        }
      ],
      "nutrition": {
        "protein_g": 30,
        "calories": 452,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2706388
      }
    },
    {
      "id": "pani-puri",
      "name": "Pani Puri",
      "slots": [
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "street-food"
      ],
      "serving": {
        "amount": 8,
        "unit": "piece"
      },
      "ingredients": [
        {
          "name": "puri"
        },
        {
          "name": "potato"
        },
        {
          "name": "chickpeas"
        },
        {
          "name": "tamarind water"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 900,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2707714
      }
    },
    {
      "id": "maharaja-thali",
      "name": "Maharaja Thali (Eat Out)",
      "slots": [
        "dinner"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "eat-out"
      ],
      "serving": {
        "amount": 1,
        "unit": "thali"
      },
      "ingredients": [
        {
          "name": "roti"
        },
        {
          "name": "dal"
        },
        {
          "name": "rice"
        },
        {
          "name": "mixed vegetables"
        }
      ],
      "nutrition": {
        "protein_g": 10,
        "calories": 400,
        "carbs_g": null,
        "fat_g": null,
        "source": "ai-estimate",
        "confidence": "low",
        "fdcId": null
      }
    },
    {
      "id": "pizza",
      "name": "Pizza",
      "slots": [
        "dinner"
      ],
      "cuisine": "Italian",
      "tags": [
        "vegetarian"
      ],
      "serving": {
        "amount": 2,
        "unit": "slice"
      },
      "ingredients": [
        {
          "name": "pizza dough"
        },
        {
          "name": "tomato sauce"
        },
        {
          "name": "cheese"
        }
      ],
      "nutrition": {
        "protein_g": 4,
        "calories": 449,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2708008
      }
    },
    {
      "id": "pan-pizza",
      "name": "Pan Pizza",
      "slots": [
        "dinner"
      ],
      "cuisine": "Italian",
      "tags": [
        "vegetarian"
      ],
      "serving": {
        "amount": 2,
        "unit": "slice"
      },
      "ingredients": [
        {
          "name": "pizza dough"
        },
        {
          "name": "tomato sauce"
        },
        {
          "name": "cheese"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 616,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 172041
      }
    },
    {
      "id": "pasta",
      "name": "Pasta",
      "slots": [
        "dinner"
      ],
      "cuisine": "Italian",
      "tags": [
        "vegetarian",
        "quick"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "pasta"
        },
        {
          "name": "tomato sauce"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 550,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2708357
      }
    },
    {
      "id": "pasta-bake",
      "name": "Pasta Bake",
      "slots": [
        "dinner"
      ],
      "cuisine": "Italian",
      "tags": [
        "vegetarian",
        "make-ahead"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "pasta"
        },
        {
          "name": "tomato sauce"
        },
        {
          "name": "cheese"
        }
      ],
      "nutrition": {
        "protein_g": 18,
        "calories": 420,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2707390
      }
    },
    {
      "id": "pasta-bolognese",
      "name": "Pasta Bolognese",
      "slots": [
        "dinner"
      ],
      "cuisine": "Italian",
      "tags": [
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "pasta"
        },
        {
          "name": "ground meat"
        },
        {
          "name": "tomato sauce"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 550,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2708357
      }
    },
    {
      "id": "garlic-parm-chicken-pasta",
      "name": "Garlic Parmesan Chicken Pasta",
      "slots": [
        "dinner"
      ],
      "cuisine": "Italian",
      "tags": [
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "pasta"
        },
        {
          "name": "chicken"
        },
        {
          "name": "parmesan cheese"
        },
        {
          "name": "garlic"
        },
        {
          "name": "cream"
        }
      ],
      "nutrition": {
        "protein_g": 45,
        "calories": 714,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 168062
      }
    },
    {
      "id": "green-goddess-pasta",
      "name": "Green Goddess Pasta",
      "slots": [
        "dinner"
      ],
      "cuisine": "Italian",
      "tags": [
        "vegetarian"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "pasta"
        },
        {
          "name": "spinach"
        },
        {
          "name": "basil"
        },
        {
          "name": "greek yogurt"
        },
        {
          "name": "garlic"
        }
      ],
      "nutrition": {
        "protein_g": 7,
        "calories": 900,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 169057
      }
    },
    {
      "id": "risotto",
      "name": "Risotto",
      "slots": [
        "dinner"
      ],
      "cuisine": "Italian",
      "tags": [
        "vegetarian"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "arborio rice"
        },
        {
          "name": "parmesan cheese"
        },
        {
          "name": "onion"
        },
        {
          "name": "vegetable broth"
        }
      ],
      "nutrition": {
        "protein_g": 18,
        "calories": 581,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2709094
      }
    },
    {
      "id": "chicken-bake",
      "name": "Chicken Bake",
      "slots": [
        "dinner"
      ],
      "cuisine": "American",
      "tags": [
        "high-protein",
        "make-ahead"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "chicken"
        },
        {
          "name": "cheese"
        },
        {
          "name": "vegetables"
        }
      ],
      "nutrition": {
        "protein_g": 25,
        "calories": 400,
        "carbs_g": null,
        "fat_g": null,
        "source": "ai-estimate",
        "confidence": "low",
        "fdcId": null
      }
    },
    {
      "id": "chicken-broccoli-nuggets",
      "name": "Chicken & Broccoli Nuggets",
      "slots": [
        "dinner"
      ],
      "cuisine": "American",
      "tags": [
        "high-protein",
        "kid-friendly"
      ],
      "serving": {
        "amount": 6,
        "unit": "piece"
      },
      "ingredients": [
        {
          "name": "chicken"
        },
        {
          "name": "broccoli"
        },
        {
          "name": "breadcrumbs"
        }
      ],
      "nutrition": {
        "protein_g": 45,
        "calories": 787,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2706087
      }
    },
    {
      "id": "burgers-fries",
      "name": "Burgers & Fries with Veggies",
      "slots": [
        "dinner"
      ],
      "cuisine": "American",
      "tags": [
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "burger"
      },
      "ingredients": [
        {
          "name": "burger bun"
        },
        {
          "name": "ground chicken"
        },
        {
          "name": "potato"
        },
        {
          "name": "vegetables"
        }
      ],
      "nutrition": {
        "protein_g": 29,
        "calories": 493,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2707481
      }
    },
    {
      "id": "burgers-poutine",
      "name": "Burgers & Poutine",
      "slots": [
        "dinner"
      ],
      "cuisine": "American",
      "tags": [
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "burger"
      },
      "ingredients": [
        {
          "name": "burger bun"
        },
        {
          "name": "ground chicken"
        },
        {
          "name": "potato"
        },
        {
          "name": "cheese curds"
        },
        {
          "name": "gravy"
        }
      ],
      "nutrition": {
        "protein_g": 29,
        "calories": 493,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2707481
      }
    },
    {
      "id": "cheesy-rice-veggies",
      "name": "Cheesy Rice with Veggies",
      "slots": [
        "dinner"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "quick"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "rice"
        },
        {
          "name": "cheese"
        },
        {
          "name": "mixed vegetables"
        }
      ],
      "nutrition": {
        "protein_g": 18,
        "calories": 392,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2709078
      }
    },
    {
      "id": "cheesy-broccoli",
      "name": "Cheesy Broccoli",
      "slots": [
        "dinner"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "side"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "broccoli"
        },
        {
          "name": "cheese"
        }
      ],
      "nutrition": {
        "protein_g": 15,
        "calories": 781,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2709656
      }
    },
    {
      "id": "butter-garlic-veggies",
      "name": "Butter Garlic Steamed Veggies",
      "slots": [
        "dinner"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "side",
        "quick"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "mixed vegetables"
        },
        {
          "name": "butter"
        },
        {
          "name": "garlic"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 228,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2706353
      }
    },
    {
      "id": "grilled-zucchini",
      "name": "Grilled Zucchini",
      "slots": [
        "dinner"
      ],
      "cuisine": "Mediterranean",
      "tags": [
        "vegetarian",
        "side",
        "quick"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "zucchini"
        },
        {
          "name": "olive oil"
        },
        {
          "name": "garlic"
        }
      ],
      "nutrition": {
        "protein_g": 18,
        "calories": 900,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2707851
      }
    },
    {
      "id": "potato-quinoa",
      "name": "Potato & Quinoa",
      "slots": [
        "dinner"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "potato"
        },
        {
          "name": "quinoa"
        }
      ],
      "nutrition": {
        "protein_g": 14,
        "calories": 599,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2709510
      }
    },
    {
      "id": "quinoa-broccoli",
      "name": "Quinoa & Broccoli",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "high-protein",
        "quick"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "quinoa"
        },
        {
          "name": "broccoli"
        }
      ],
      "nutrition": {
        "protein_g": 15,
        "calories": 420,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 168917
      }
    },
    {
      "id": "rice-a-roni",
      "name": "Rice-a-Roni",
      "slots": [
        "dinner"
      ],
      "cuisine": "American",
      "tags": [
        "vegetarian",
        "quick"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "rice"
        },
        {
          "name": "pasta"
        },
        {
          "name": "seasoning"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 900,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 173347
      }
    },
    {
      "id": "taco",
      "name": "Tacos",
      "slots": [
        "dinner"
      ],
      "cuisine": "Mexican",
      "tags": [
        "high-protein"
      ],
      "serving": {
        "amount": 2,
        "unit": "taco"
      },
      "ingredients": [
        {
          "name": "tortilla"
        },
        {
          "name": "beans"
        },
        {
          "name": "ground chicken"
        },
        {
          "name": "cheese"
        },
        {
          "name": "lettuce"
        }
      ],
      "nutrition": {
        "protein_g": 13,
        "calories": 340,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 170736
      }
    },
    {
      "id": "mexican-rice-bowl",
      "name": "Mexican Rice Bowl",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "Mexican",
      "tags": [
        "vegetarian",
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "rice"
        },
        {
          "name": "beans"
        },
        {
          "name": "guacamole"
        },
        {
          "name": "pico de gallo"
        },
        {
          "name": "cheese"
        }
      ],
      "nutrition": {
        "protein_g": 12,
        "calories": 683,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 169031
      }
    },
    {
      "id": "nachos",
      "name": "Nachos",
      "slots": [
        "dinner"
      ],
      "cuisine": "Mexican",
      "tags": [
        "vegetarian"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "tortilla chips"
        },
        {
          "name": "cheese"
        },
        {
          "name": "beans"
        },
        {
          "name": "salsa"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 900,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2708580
      }
    },
    {
      "id": "cauliflower-enchilada",
      "name": "Cauliflower Enchilada",
      "slots": [
        "dinner"
      ],
      "cuisine": "Mexican",
      "tags": [
        "vegetarian"
      ],
      "serving": {
        "amount": 2,
        "unit": "piece"
      },
      "ingredients": [
        {
          "name": "cauliflower"
        },
        {
          "name": "tortilla"
        },
        {
          "name": "enchilada sauce"
        },
        {
          "name": "cheese"
        }
      ],
      "nutrition": {
        "protein_g": 16,
        "calories": 306,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2708566
      }
    },
    {
      "id": "greek-meal",
      "name": "Greek Meal",
      "slots": [
        "dinner"
      ],
      "cuisine": "Mediterranean",
      "tags": [
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "chicken"
        },
        {
          "name": "pita"
        },
        {
          "name": "tzatziki"
        },
        {
          "name": "cucumber"
        },
        {
          "name": "tomato"
        }
      ],
      "nutrition": {
        "protein_g": 37,
        "calories": 900,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 172750
      }
    },
    {
      "id": "shawarma",
      "name": "Shawarma",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "Middle Eastern",
      "tags": [
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "wrap"
      },
      "ingredients": [
        {
          "name": "chicken"
        },
        {
          "name": "pita"
        },
        {
          "name": "garlic sauce"
        },
        {
          "name": "vegetables"
        }
      ],
      "nutrition": {
        "protein_g": 25,
        "calories": 400,
        "carbs_g": null,
        "fat_g": null,
        "source": "ai-estimate",
        "confidence": "low",
        "fdcId": null
      }
    },
    {
      "id": "falafel",
      "name": "Falafel",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "Mediterranean",
      "tags": [
        "vegetarian",
        "high-protein"
      ],
      "serving": {
        "amount": 4,
        "unit": "piece"
      },
      "ingredients": [
        {
          "name": "chickpeas"
        },
        {
          "name": "garlic"
        },
        {
          "name": "herbs"
        },
        {
          "name": "pita"
        }
      ],
      "nutrition": {
        "protein_g": 26,
        "calories": 900,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2707408
      }
    },
    {
      "id": "asian-stir-fry-noodles",
      "name": "Asian Stir Fry Noodles",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "Asian",
      "tags": [
        "vegetarian",
        "quick"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "noodles"
        },
        {
          "name": "mixed vegetables"
        },
        {
          "name": "soy sauce"
        },
        {
          "name": "garlic"
        }
      ],
      "nutrition": {
        "protein_g": 7,
        "calories": 249,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2710036
      }
    },
    {
      "id": "pad-thai",
      "name": "Pad Thai",
      "slots": [
        "dinner"
      ],
      "cuisine": "Asian",
      "tags": [
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "rice noodles"
        },
        {
          "name": "tofu"
        },
        {
          "name": "peanuts"
        },
        {
          "name": "egg"
        },
        {
          "name": "bean sprouts"
        }
      ],
      "nutrition": {
        "protein_g": 28,
        "calories": 539,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2708806
      }
    },
    {
      "id": "tofu-bowl-chili-paneer",
      "name": "Tofu Bowl with Chili Paneer",
      "slots": [
        "dinner"
      ],
      "cuisine": "Asian",
      "tags": [
        "vegetarian",
        "high-protein"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "tofu"
        },
        {
          "name": "paneer"
        },
        {
          "name": "bell pepper"
        },
        {
          "name": "soy sauce"
        }
      ],
      "nutrition": {
        "protein_g": 12,
        "calories": 329,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 167722
      }
    },
    {
      "id": "din-tai-fung",
      "name": "Din Tai Fung Dumplings (Eat Out)",
      "slots": [
        "dinner"
      ],
      "cuisine": "Asian",
      "tags": [
        "eat-out"
      ],
      "serving": {
        "amount": 6,
        "unit": "piece"
      },
      "ingredients": [
        {
          "name": "dumplings"
        },
        {
          "name": "soy sauce"
        }
      ],
      "nutrition": {
        "protein_g": 2,
        "calories": 715,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2710677
      }
    },
    {
      "id": "rice-bowl",
      "name": "Rice Bowl",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "American",
      "tags": [
        "quick",
        "customizable"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "rice"
        },
        {
          "name": "mixed vegetables"
        },
        {
          "name": "beans"
        }
      ],
      "nutrition": {
        "protein_g": 20,
        "calories": 543,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2708561
      }
    },
    {
      "id": "puda",
      "name": "Puda (Savory Veggie Pancakes)",
      "slots": [
        "breakfast",
        "lunch"
      ],
      "cuisine": "Indian",
      "tags": [
        "vegetarian",
        "quick",
        "high-protein",
        "simple-lunch"
      ],
      "serving": {
        "amount": 2,
        "unit": "piece"
      },
      "ingredients": [
        {
          "name": "gram flour"
        },
        {
          "name": "onion"
        },
        {
          "name": "tomato"
        },
        {
          "name": "spinach"
        },
        {
          "name": "green chili"
        }
      ],
      "nutrition": {
        "protein_g": 25,
        "calories": 400,
        "carbs_g": null,
        "fat_g": null,
        "source": "ai-estimate",
        "confidence": "low",
        "fdcId": null
      }
    },
    {
      "id": "greek-salad-protein",
      "name": "Greek Salad with Chicken or Chickpeas",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "Mediterranean",
      "tags": [
        "high-protein",
        "make-ahead",
        "simple-lunch",
        "salad"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "cucumber"
        },
        {
          "name": "tomato"
        },
        {
          "name": "feta cheese"
        },
        {
          "name": "olives"
        },
        {
          "name": "chickpeas"
        },
        {
          "name": "chicken"
        }
      ],
      "nutrition": {
        "protein_g": 10,
        "calories": 168,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2709830
      }
    },
    {
      "id": "coleslaw-bowl-protein",
      "name": "Coleslaw Bowl with Grilled Chicken",
      "slots": [
        "lunch",
        "dinner"
      ],
      "cuisine": "American",
      "tags": [
        "high-protein",
        "make-ahead",
        "simple-lunch",
        "salad"
      ],
      "serving": {
        "amount": 1,
        "unit": "bowl"
      },
      "ingredients": [
        {
          "name": "cabbage"
        },
        {
          "name": "carrot"
        },
        {
          "name": "mayonnaise"
        },
        {
          "name": "chicken"
        }
      ],
      "nutrition": {
        "protein_g": 3,
        "calories": 410,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2709815
      }
    },
    {
      "id": "sing-tong-thai",
      "name": "Sing Tong Thai (Eat Out)",
      "slots": [
        "dinner"
      ],
      "cuisine": "Thai",
      "tags": [
        "eat-out",
        "backup"
      ],
      "serving": {
        "amount": 1,
        "unit": "plate"
      },
      "ingredients": [
        {
          "name": "rice noodles"
        },
        {
          "name": "vegetables"
        },
        {
          "name": "tofu"
        }
      ],
      "nutrition": {
        "protein_g": 4,
        "calories": 296,
        "carbs_g": null,
        "fat_g": null,
        "source": "usda-fdc",
        "confidence": "low",
        "fdcId": 2709744
      }
    }
  ]
};
